language: c

cache: apt

sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_script:
  - export CFLAGS="-Wall -Wextra -Werror"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap PX4/homebrew-px4; brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libusb fftw gcc-arm-none-eabi dfu-util; fi
  # For virtualenv(?) reasons we can't apt-get install python-yaml
  - pip install PyYAML

script:
  - mkdir host/build
  - cd host/build
  - cmake ..
  - make
  - cd ../../firmware/libopencm3
  - make
  - cd ../hackrf_usb
  - mkdir build
  - cd build
  - cmake ..
  - make

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libusb-1.0-0-dev
      - libfftw3-dev
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - dfu-util
